server:
  port: 8086
  servlet:
    context-path: /krEconoMon
  compression:
    enabled: true
    mime-types: application/json,application/javascript,text/css,text/html
    min-response-size: 1024

spring:
  application:
    name: kr-economy-mon
  profiles:
    active: prod
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    open-in-view: false

logging:
  level:
    com.example.kreconomonmon: DEBUG
